version: '3'

services:
  php:
    image: sun7pro/magento2-php-fpm:php7.4
    restart: always
    working_dir: /var/www/html/magento
    volumes:
        - ./:/var/www/html/magento
        - ./dev/docker/images/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    depends_on:
        - mysql
        - redis
        - rabbitmq
        - elasticsearch
    expose:
        - "9000"
    environment:
        HOST_UID: 0
        HOST_GID: 0
    networks:
      - magento
  nginx:
    restart: always
    image: nginx:1
    working_dir: /var/www/html/magento
    volumes:
        - ./:/var/www/html/magento
        - ./dev/docker/images/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - mysql
    ports:
        - "8011:80"
    networks:
      - magento
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - magento

  mysql:
    container_name: mysql
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./dev/docker/data/mysql:/var/lib/mysql
      - ./dev/docker/images/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3306:3306"
    networks:
      - magento
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - magento
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - magento

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - magento
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

networks:
  magento:
    driver: bridge
volumes:
  mysql:

