version: '3'

services:
  php:
    image: sun7pro/magento2-php-fpm:php7.4
    restart: always
    working_dir: /var/www/html/magento
    volumes:
        - ./:/var/www/html/magento
        - ./dev/docker/images/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    expose:
        - "9000"
    environment:
        HOST_UID: 0
        HOST_GID: 0
    networks:
      - magento
  nginx:
    restart: always
    image: nginx:1
    working_dir: /var/www/html/magento
    volumes:
        - ./:/var/www/html/magento
        - ./dev/docker/images/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8011:80"
    networks:
      - magento
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - magento

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    volumes:
      - ./dev/docker/data/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: 'magento_db'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: 'son'
      MYSQL_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - "3308:3306"
    networks:
      - magento

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /sessions
    external_links:
      - mysql
    depends_on:
      - mysql
      - redis
    networks:
      - magento

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - magento

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - magento
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

networks:
  magento:
    driver: bridge
